Repository luscinia-enterprises/aristotle-api, pull requests merged in 2021-07, with the labels that each got.

#21 Added db functionality
  api/controller/endpoints.py
  api/controller/routes.py
  api/models/User.py
  requirements.txt
Labels: enhancement

#24 Removed id field from models and removed references to id
  api/controller/endpoints.py
  api/models/Admin.py
  api/models/Course.py
  api/models/Lesson.py
  api/models/Token.py
  api/models/User.py
  api/models/user/LoginRecord.py
  api/models/user/SecurityQuestion.py
Labels: enhancement, security findings

#27 Update CI/CD Workflows
  .github/workflows/anchore-analysis.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/shiftleft-analysis.yml
  .github/workflows/shiftleft.yml
  shiftleft.yml
Labels: enhancement, security findings

#30 Removed debug mode
  app.py
Labels: bug

#33 Token authentication
  .gitignore
  api/controller/__init__.py
  api/controller/resource.py
  api/services/auth/auth.py
  api/services/utils/cache.py
  app.py
Labels: enhancement
